name: Validate Homey App
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm run smoke:packaged-build
      - uses: athombv/github-action-homey-app-validate@002b7273c2b86032cb20d9bf25a67c8daca13f2c # v1
        with:
          level: verified
